"use client"
import { useState } from 'react'
import Navbar from './components/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  const [isLightMode, setIsLightMode] = useState(false);
  const toggleMode = ()=>{setIsLightMode(!isLightMode)};
  return (
    <html lang="en">
      <head>
      <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />
      </head>
      <body className={inter.className}>
        <Navbar mode={isLightMode} toggleMode={toggleMode}/>
        {children}
        </body>
    </html>
  )
}
